CREATE TABLE USUARIO 
   (    ID_USUARIO NUMBER(4,0) NOT NULL PRIMARY KEY, 
	USUARIO VARCHAR2(20 BYTE) NOT NULL UNIQUE, 
	CLAVE VARCHAR2(80 BYTE) NOT NULL , 
	NOMBRE VARCHAR2(120 BYTE)NOT NULL,
	ESTADO CHAR(1 BYTE) DEFAULT 1 NOT NULL
    );
CREATE SEQUENCE SEQ_USUARIO;
  
INSERT INTO USUARIO(ID_USUARIO ,USUARIO,CLAVE,NOMBRE)
VALUES(SEQ_USUARIO.NEXTVAL,'ADMIN','123','ADMINISTRADOR');
 INSERT INTO USUARIO(ID_USUARIO ,USUARIO,CLAVE,NOMBRE)
VALUES(SEQ_USUARIO.NEXTVAL,'DEMO','abc','DEMO');
COMMIT;

SELECT ID_USUARIO ,USUARIO,CLAVE,NOMBRE FROM USUARIO;
