CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMERIC(4) NOT NULL ,
    NOMBRES VARCHAR2(240) NOT NULL,
    ROL VARCHAR2(240) NOT NULL,
    ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

--CREATE SEQUENCE SEQ_EMPLEADO;

INSERT INTO EMPLEADO(ID_EMPLEADO, NOMBRES, ROL) VALUES (SEQ_EMPLEADO.nextval, 'ASTRID MIMBELA', 'DOCENTE');
INSERT INTO EMPLEADO(ID_EMPLEADO, NOMBRES, ROL) VALUES (SEQ_EMPLEADO.nextval, 'RAQUEL REYES', 'CAJERA');
INSERT INTO EMPLEADO(ID_EMPLEADO, NOMBRES, ROL) VALUES (SEQ_EMPLEADO.nextval, 'YAJAIRA BURGA', 'TECNÓLOGA MÉDICA');